server:
    port: 8080
#    address: 127.0.0.1
#    sessionTimeout:
spring:
    data.solr:
        host: http://127.0.0.1:8983/solr
        zk-host:
        repositories.enabled: true
    jpa:
        hibernate.ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:mysql://localhost/license_plate_search
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: root